pipeline {

    environment {
     GITHUB_URL='github.com/kevinmenotyou/devops_project2'
    }
  
    agent {
        node {
            label 'test-jenkins-agent1'
        }
    }

    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }


    stages {
        stage('Diagram') {
			when {
				allOf {
					changeset "diagram/*"
				}
			}
			steps {
				echo 'Building Diagram..'
				sh 'pip3 install diagrams'
				sh 'python3 diagram/diagram.py'
				sh """ 
					git config --global user.email "fake@fakeemail.com"
					git config --global user.name "SVC_ROBOTUSER"
					git add output
					git commit -m '[robot] Submit updated diagram from build machine'
					git push https://$USERNAME:$PASSWORD@$GITHUB_URL origin HEAD
				"""
			}
        }
    }
}