pipeline {

    environment {
     GITHUB_API_URL='https://api.github.com/repos/kevinmenotyou/devops_assignment2'
    }
  
    agent {
        node {
            label 'test-jenkins-agent1'
        }
    }

    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }


    stages {
        stage('Diagram') {
			when {
				allOf {
					changeset "diagram/*"
				}
			}
			steps {
				echo 'Building Diagram..'
				sh 'py diagram/diagram.py'
				sh 'git add output'
				sh 'git commit -m "[robot] Submit updated diagram from build machine"'
				sh 'git push origin HEAD'
			}
        }
    }
}