pipeline {

    environment {
     GITHUB_URL='github.com/kevinmenotyou/devops_project2'
    }
  
    agent {
        node {
            label 'test-jenkins-agent1'
        }
    }

    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }


    stages {
        stage('Diagram') {
			when {
				allOf {
					changeset "diagram/*"
				}
			}
			steps {
				withCredentials([usernamePassword(credentialsId: '167b833a-9420-453a-a1a3-4633984c9443', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
					echo 'Building Diagram..'
					sh """ 
						git config --global user.email "fake@fakeemail.com"
						git config --global user.name "SVC_ROBOTUSER"
						git fetch origin pull/$CHANGE_ID/head:generated
						pip3 install diagrams
						python3 diagram/diagram.py
						git add output
						git commit -m '[robot] Submit updated diagram from build machine'
						git push https://$USERNAME:$PASSWORD@$GITHUB_URL
					"""
				}
			}
        }
    }
}